version: 2

sources:
  - name: raw
    schema: gwz_raw_data
    description: all data
    tables:
      - name: sales
        identifier: raw_gz_sales
        description: all sales
      - name: product
        identifier: raw_gz_product
        description: all product types
        columns:
          - name: products_id
            description: primary key
            tests:
              - unique
              - not_null               
          - name: purchase_price
            tests:
              - unique
              - not_null
      - name: ship
        identifier: raw_gz_ship
        description: all shipping information
